// ─────────────────────────────────────────────
//  GAME DATA  –  VerseMemory, Trivia, Scramble
// ─────────────────────────────────────────────

// ── Verse Memory: fill in the blank ──────────
export const verseMemoryData = [
  {
    reference: "John 3:16",
    display: "For God so loved the world that he gave his one and only ______, that whoever believes in him shall not perish but have eternal life.",
    blankWord: "Son",
    options: ["Son", "Word", "Spirit", "Light"],
  },
  {
    reference: "Psalm 23:1",
    display: "The LORD is my ______; I shall not want.",
    blankWord: "shepherd",
    options: ["shepherd", "king", "father", "rock"],
  },
  {
    reference: "Proverbs 3:5",
    display: "Trust in the LORD with all your ______ and lean not on your own understanding.",
    blankWord: "heart",
    options: ["heart", "mind", "soul", "strength"],
  },
  {
    reference: "Romans 8:28",
    display: "And we know that in all things God works for the good of those who love him, who have been called according to his ______.",
    blankWord: "purpose",
    options: ["purpose", "will", "glory", "plan"],
  },
  {
    reference: "Philippians 4:13",
    display: "I can do all this through him who gives me ______.",
    blankWord: "strength",
    options: ["strength", "wisdom", "hope", "grace"],
  },
  {
    reference: "Genesis 1:1",
    display: "In the ______ God created the heavens and the earth.",
    blankWord: "beginning",
    options: ["beginning", "darkness", "first day", "void"],
  },
  {
    reference: "Jeremiah 29:11",
    display: "For I know the plans I have for you, declares the LORD, plans to ______ you and not to harm you, plans to give you hope and a future.",
    blankWord: "prosper",
    options: ["prosper", "bless", "teach", "redeem"],
  },
  {
    reference: "Isaiah 40:31",
    display: "But those who hope in the LORD will renew their strength. They will soar on wings like ______.",
    blankWord: "eagles",
    options: ["eagles", "doves", "sparrows", "hawks"],
  },
  {
    reference: "Matthew 5:3",
    display: "Blessed are the poor in ______, for theirs is the kingdom of heaven.",
    blankWord: "spirit",
    options: ["spirit", "heart", "deed", "faith"],
  },
  {
    reference: "Psalm 119:105",
    display: "Your word is a ______ to my feet and a light to my path.",
    blankWord: "lamp",
    options: ["lamp", "guide", "fire", "star"],
  },
  {
    reference: "Romans 6:23",
    display: "For the wages of sin is death, but the gift of God is eternal ______ in Christ Jesus our Lord.",
    blankWord: "life",
    options: ["life", "peace", "joy", "rest"],
  },
  {
    reference: "Ephesians 2:8",
    display: "For it is by ______ you have been saved, through faith—and this is not from yourselves, it is the gift of God.",
    blankWord: "grace",
    options: ["grace", "works", "faith", "love"],
  },
  {
    reference: "Joshua 1:9",
    display: "Have I not commanded you? Be strong and ______. Do not be afraid; do not be discouraged.",
    blankWord: "courageous",
    options: ["courageous", "faithful", "patient", "humble"],
  },
  {
    reference: "John 14:6",
    display: "Jesus answered, I am the way and the truth and the ______. No one comes to the Father except through me.",
    blankWord: "life",
    options: ["life", "light", "door", "vine"],
  },
  {
    reference: "Proverbs 22:6",
    display: "Start children off on the way they should go, and even when they are old they will not ______ from it.",
    blankWord: "turn",
    options: ["turn", "stray", "fall", "run"],
  },
  {
    reference: "Matthew 6:33",
    display: "But seek first his kingdom and his ______, and all these things will be given to you as well.",
    blankWord: "righteousness",
    options: ["righteousness", "glory", "wisdom", "grace"],
  },
  {
    reference: "Psalm 46:1",
    display: "God is our refuge and ______, an ever-present help in trouble.",
    blankWord: "strength",
    options: ["strength", "shield", "tower", "rock"],
  },
  {
    reference: "2 Timothy 3:16",
    display: "All ______ is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness.",
    blankWord: "Scripture",
    options: ["Scripture", "wisdom", "prayer", "doctrine"],
  },
  {
    reference: "Hebrews 11:1",
    display: "Now faith is confidence in what we ______ for and assurance about what we do not see.",
    blankWord: "hope",
    options: ["hope", "ask", "pray", "wait"],
  },
  {
    reference: "1 Corinthians 13:4",
    display: "Love is ______ and kind; love does not envy or boast.",
    blankWord: "patient",
    options: ["patient", "gentle", "joyful", "humble"],
  },
];

// ── Bible Trivia ──────────────────────────────
export const trivia = [
  {
    question: "How many books are in the Bible?",
    options: ["60", "64", "66", "72"],
    correctIndex: 2,
  },
  {
    question: "Who was swallowed by a great fish?",
    options: ["Elijah", "Jonah", "Daniel", "Moses"],
    correctIndex: 1,
  },
  {
    question: "How many days and nights did it rain during Noah's flood?",
    options: ["20", "30", "40", "50"],
    correctIndex: 2,
  },
  {
    question: "Who denied Jesus three times?",
    options: ["John", "Thomas", "Judas", "Peter"],
    correctIndex: 3,
  },
  {
    question: "What was the first miracle Jesus performed?",
    options: ["Healing the blind", "Turning water into wine", "Walking on water", "Feeding 5,000"],
    correctIndex: 1,
  },
  {
    question: "Who was the first king of Israel?",
    options: ["David", "Solomon", "Saul", "Samuel"],
    correctIndex: 2,
  },
  {
    question: "Which disciple betrayed Jesus for 30 pieces of silver?",
    options: ["Peter", "James", "Judas", "Thomas"],
    correctIndex: 2,
  },
  {
    question: "In which city was Jesus born?",
    options: ["Jerusalem", "Nazareth", "Bethlehem", "Jericho"],
    correctIndex: 2,
  },
  {
    question: "How many Psalms are in the Bible?",
    options: ["100", "120", "150", "180"],
    correctIndex: 2,
  },
  {
    question: "Who built the ark?",
    options: ["Abraham", "Moses", "Noah", "Adam"],
    correctIndex: 2,
  },
  {
    question: "What is the shortest verse in the Bible?",
    options: ["God is love.", "Jesus wept.", "Pray without ceasing.", "Fear not."],
    correctIndex: 1,
  },
  {
    question: "Who wrote most of the New Testament letters?",
    options: ["Peter", "John", "James", "Paul"],
    correctIndex: 3,
  },
  {
    question: "How many apostles did Jesus have?",
    options: ["7", "10", "12", "14"],
    correctIndex: 2,
  },
  {
    question: "Which book comes first in the New Testament?",
    options: ["Mark", "Luke", "John", "Matthew"],
    correctIndex: 3,
  },
  {
    question: "What was the name of Moses' brother?",
    options: ["Aaron", "Joshua", "Caleb", "Eli"],
    correctIndex: 0,
  },
  {
    question: "Which sea did Moses part?",
    options: ["Dead Sea", "Sea of Galilee", "Red Sea", "Mediterranean Sea"],
    correctIndex: 2,
  },
  {
    question: "How many days was Jesus in the tomb before rising?",
    options: ["1", "2", "3", "7"],
    correctIndex: 2,
  },
  {
    question: "Who wrote the Book of Revelation?",
    options: ["Paul", "Peter", "James", "John"],
    correctIndex: 3,
  },
  {
    question: "What was the name of Abraham's wife?",
    options: ["Rachel", "Ruth", "Sarah", "Rebekah"],
    correctIndex: 2,
  },
  {
    question: "In what river was Jesus baptized?",
    options: ["Nile", "Euphrates", "Jordan", "Galilee"],
    correctIndex: 2,
  },
  {
    question: "Who was David's son known for his wisdom?",
    options: ["Absalom", "Solomon", "Nathan", "Rehoboam"],
    correctIndex: 1,
  },
  {
    question: "How many people were fed with five loaves and two fish?",
    options: ["3,000", "4,000", "5,000", "7,000"],
    correctIndex: 2,
  },
  {
    question: "Which prophet was taken to heaven in a chariot of fire?",
    options: ["Elisha", "Isaiah", "Elijah", "Ezekiel"],
    correctIndex: 2,
  },
  {
    question: "What was Job known for?",
    options: ["His wealth", "His patience in suffering", "His prophecies", "His many sons"],
    correctIndex: 1,
  },
  {
    question: "Who was the first man created by God?",
    options: ["Cain", "Seth", "Abel", "Adam"],
    correctIndex: 3,
  },
  {
    question: "Which book records the Ten Commandments for the first time?",
    options: ["Genesis", "Leviticus", "Exodus", "Deuteronomy"],
    correctIndex: 2,
  },
  {
    question: "What language was most of the Old Testament written in?",
    options: ["Greek", "Latin", "Aramaic", "Hebrew"],
    correctIndex: 3,
  },
  {
    question: "Who replaced Judas Iscariot as the 12th apostle?",
    options: ["Barnabas", "Matthias", "Timothy", "Silas"],
    correctIndex: 1,
  },
  {
    question: "How many days did God take to create the world (including rest)?",
    options: ["5", "6", "7", "8"],
    correctIndex: 2,
  },
  {
    question: "What did Daniel refuse to eat in Babylon?",
    options: ["Bread", "Fish", "The king's food", "Fruit"],
    correctIndex: 2,
  },
  {
    question: "Which woman hid the Israelite spies in Jericho?",
    options: ["Deborah", "Rahab", "Miriam", "Hannah"],
    correctIndex: 1,
  },
  {
    question: "Who was the first Christian martyr?",
    options: ["James", "John", "Stephen", "Peter"],
    correctIndex: 2,
  },
  {
    question: "What symbol did God give as a sign of his covenant with Noah?",
    options: ["A dove", "A rainbow", "A star", "A cloud"],
    correctIndex: 1,
  },
  {
    question: "How many times did God call Samuel before Eli realized it was God?",
    options: ["1", "2", "3", "4"],
    correctIndex: 2,
  },
  {
    question: "Which book is the longest in the Bible?",
    options: ["Isaiah", "Genesis", "Jeremiah", "Psalms"],
    correctIndex: 3,
  },
  {
    question: "Which book is the shortest in the Bible?",
    options: ["3 John", "Philemon", "Obadiah", "Jude"],
    correctIndex: 0,
  },
  {
    question: "What was the name of the garden where Jesus was arrested?",
    options: ["Eden", "Gethsemane", "Olive", "Babylon"],
    correctIndex: 1,
  },
  {
    question: "Who was the last judge of Israel before the kings?",
    options: ["Gideon", "Samson", "Samuel", "Eli"],
    correctIndex: 2,
  },
  {
    question: "What was Paul's name before his conversion?",
    options: ["Silas", "Saul", "Simon", "Seth"],
    correctIndex: 1,
  },
  {
    question: "In how many languages was the sign on Jesus' cross written?",
    options: ["1", "2", "3", "4"],
    correctIndex: 2,
  },
];

// ── Word Scramble ─────────────────────────────
export const scrambleWords = [
  { word: "MOSES", hint: "Led Israel out of Egypt", category: "Person" },
  { word: "SAMSON", hint: "Known for great strength", category: "Person" },
  { word: "DAVID", hint: "Killed Goliath as a boy", category: "Person" },
  { word: "GOLIATH", hint: "Giant Philistine warrior", category: "Person" },
  { word: "SOLOMON", hint: "Wisest king of Israel", category: "Person" },
  { word: "ELIJAH", hint: "Called fire from heaven", category: "Person" },
  { word: "DANIEL", hint: "Survived the lion's den", category: "Person" },
  { word: "ESTHER", hint: "Jewish queen who saved her people", category: "Person" },
  { word: "JONAH", hint: "Spent three days in a fish", category: "Person" },
  { word: "ABRAHAM", hint: "Father of many nations", category: "Person" },
  { word: "JERUSALEM", hint: "City of David, holy capital", category: "Place" },
  { word: "BETHLEHEM", hint: "Birthplace of Jesus", category: "Place" },
  { word: "NAZARETH", hint: "Where Jesus grew up", category: "Place" },
  { word: "GALILEE", hint: "Region where Jesus ministered", category: "Place" },
  { word: "JORDAN", hint: "River where Jesus was baptized", category: "Place" },
  { word: "JERICHO", hint: "City whose walls fell down", category: "Place" },
  { word: "EGYPT", hint: "Where Israel was enslaved", category: "Place" },
  { word: "BABYLON", hint: "Empire that exiled Judah", category: "Place" },
  { word: "GENESIS", hint: "First book of the Bible", category: "Book" },
  { word: "PSALMS", hint: "Book of songs and praises", category: "Book" },
  { word: "PROVERBS", hint: "Book of wisdom sayings", category: "Book" },
  { word: "ISAIAH", hint: "Major prophet, spoke of the Messiah", category: "Book" },
  { word: "MATTHEW", hint: "First gospel written for Jews", category: "Book" },
  { word: "ROMANS", hint: "Paul's letter about justification", category: "Book" },
  { word: "REVELATION", hint: "Final book of the Bible", category: "Book" },
  { word: "ACTS", hint: "History of the early church", category: "Book" },
  { word: "BAPTISM", hint: "Sacrament using water", category: "Word" },
  { word: "COVENANT", hint: "A solemn agreement with God", category: "Word" },
  { word: "GOSPEL", hint: "Good news of Jesus Christ", category: "Word" },
  { word: "PENTECOST", hint: "Day the Holy Spirit came", category: "Word" },
  { word: "PROPHET", hint: "Messenger who speaks for God", category: "Word" },
  { word: "SALVATION", hint: "Being saved from sin", category: "Word" },
  { word: "PARABLE", hint: "A short story with a spiritual meaning", category: "Word" },
  { word: "DISCIPLE", hint: "A follower of Jesus", category: "Word" },
];

// ── Daily Verse Pool ──────────────────────────
export const dailyVerses = [
  { reference: "John 3:16", text: "For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life." },
  { reference: "Psalm 23:1", text: "The LORD is my shepherd; I shall not want." },
  { reference: "Proverbs 3:5-6", text: "Trust in the LORD with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight." },
  { reference: "Jeremiah 29:11", text: "For I know the plans I have for you, declares the LORD, plans to prosper you and not to harm you, plans to give you hope and a future." },
  { reference: "Romans 8:28", text: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose." },
  { reference: "Isaiah 40:31", text: "But those who hope in the LORD will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint." },
  { reference: "Philippians 4:13", text: "I can do all this through him who gives me strength." },
  { reference: "Philippians 4:6-7", text: "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus." },
  { reference: "Joshua 1:9", text: "Have I not commanded you? Be strong and courageous. Do not be afraid; do not be discouraged, for the LORD your God will be with you wherever you go." },
  { reference: "Matthew 6:33", text: "But seek first his kingdom and his righteousness, and all these things will be given to you as well." },
  { reference: "Psalm 46:1", text: "God is our refuge and strength, an ever-present help in trouble." },
  { reference: "Romans 12:2", text: "Do not conform to the pattern of this world, but be transformed by the renewing of your mind." },
  { reference: "2 Timothy 1:7", text: "For God has not given us a spirit of fear, but of power and of love and of a sound mind." },
  { reference: "Hebrews 11:1", text: "Now faith is confidence in what we hope for and assurance about what we do not see." },
  { reference: "1 Corinthians 13:4-5", text: "Love is patient, love is kind. It does not envy, it does not boast, it is not proud. It does not dishonor others, it is not self-seeking, it is not easily angered, it keeps no record of wrongs." },
  { reference: "Psalm 119:105", text: "Your word is a lamp for my feet, a light on my path." },
  { reference: "Ephesians 2:8-9", text: "For it is by grace you have been saved, through faith—and this is not from yourselves, it is the gift of God—not by works, so that no one can boast." },
  { reference: "Matthew 5:14", text: "You are the light of the world. A town built on a hill cannot be hidden." },
  { reference: "Galatians 2:20", text: "I have been crucified with Christ and I no longer live, but Christ lives in me." },
  { reference: "Romans 6:23", text: "For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord." },
  { reference: "Lamentations 3:22-23", text: "Because of the LORD's great love we are not consumed, for his compassions never fail. They are new every morning; great is your faithfulness." },
  { reference: "Psalm 27:1", text: "The LORD is my light and my salvation—whom shall I fear? The LORD is the stronghold of my life—of whom shall I be afraid?" },
  { reference: "John 14:6", text: "Jesus answered, 'I am the way and the truth and the life. No one comes to the Father except through me.'" },
  { reference: "2 Corinthians 5:17", text: "Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!" },
  { reference: "Psalm 34:8", text: "Taste and see that the LORD is good; blessed is the one who takes refuge in him." },
  { reference: "Romans 10:9", text: "If you declare with your mouth, 'Jesus is Lord,' and believe in your heart that God raised him from the dead, you will be saved." },
  { reference: "Matthew 11:28", text: "Come to me, all you who are weary and burdened, and I will give you rest." },
  { reference: "Psalm 91:1-2", text: "Whoever dwells in the shelter of the Most High will rest in the shadow of the Almighty. I will say of the LORD, 'He is my refuge and my fortress, my God, in whom I trust.'" },
  { reference: "James 1:2-3", text: "Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds, because you know that the testing of your faith produces perseverance." },
  { reference: "Proverbs 16:3", text: "Commit to the LORD whatever you do, and he will establish your plans." },
  { reference: "Isaiah 41:10", text: "So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand." },
  { reference: "Psalm 16:8", text: "I keep my eyes always on the LORD. With him at my right hand, I will not be shaken." },
  { reference: "1 John 4:19", text: "We love because he first loved us." },
  { reference: "Colossians 3:23", text: "Whatever you do, work at it with all your heart, as working for the Lord, not for human masters." },
  { reference: "Acts 1:8", text: "But you will receive power when the Holy Spirit comes on you; and you will be my witnesses in Jerusalem, and in all Judea and Samaria, and to the ends of the earth." },
  { reference: "John 1:1", text: "In the beginning was the Word, and the Word was with God, and the Word was God." },
  { reference: "Romans 5:8", text: "But God demonstrates his own love for us in this: While we were still sinners, Christ died for us." },
  { reference: "Deuteronomy 31:6", text: "Be strong and courageous. Do not be afraid or terrified because of them, for the LORD your God goes with you; he will never leave you nor forsake you." },
];
